# Generated by Django 5.2.8 on 2025-11-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=10)),
                ('periodo', models.DateField()),
                ('fonte', models.CharField(max_length=100)),
            ],
        ),
    ]
