# Generated by Django 5.2.8 on 2025-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_indicador_delete_indicadoreconomico'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='percentual_lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
